package.json
src/assets/t9n/instant-apps-interactive-legend/resources.json
src/assets/t9n/instant-apps-interactive-legend/resources_en.json
src/components.d.ts
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-caption/instant-apps-interactive-legend-caption.scss
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-caption/instant-apps-interactive-legend-caption.tsx
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-caption/readme.md
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-classic/instant-apps-interactive-legend-classic.scss
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-classic/instant-apps-interactive-legend-classic.tsx
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-classic/interfaces/interfaces.d.ts
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-layer-caption/instant-apps-interactive-legend-layer-caption.tsx
src/components/instant-apps-interactive-legend/support/helpers.ts

Removed layer switcher, rendering layer legends in a single panel, implemented collapsible sections for legend layers, ui interaction logic updates with single symbol drawing style, css tweaks and bug fixes

instant-apps-interactive-legend: 2023.r01

---

CHANGELOG.md
package.json
src/components.d.ts
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-classic/instant-apps-interactive-legend-classic.scss
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-classic/instant-apps-interactive-legend-classic.tsx
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-count/instant-apps-interactive-legend-count.scss
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-count/instant-apps-interactive-legend-count.tsx
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-count/readme.md
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-layer-caption/instant-apps-interactive-legend-layer-caption.tsx
src/components/instant-apps-interactive-legend/support/helpers.ts

Bug fixes:
- Feature count
- Hover/selection color states
- Show all, zoom to, and feature count for legend elements with one info

instant-apps-interactive-legend

---

CHANGELOG.md
package.json
src/components/instant-apps-social-share/instant-apps-social-share.scss
src/components/instant-apps-social-share/instant-apps-social-share.tsx

Explicitly set `text-align: left` text within textarea of embed mode while in RTL languages.

instant-apps-social-share t9n

---

CHANGELOG.md
package.json
src/components.d.ts
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-caption/instant-apps-interactive-legend-caption.scss
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-caption/instant-apps-interactive-legend-caption.tsx
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-caption/readme.md
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-classic/instant-apps-interactive-legend-classic.scss
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-classic/instant-apps-interactive-legend-classic.tsx
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-layer-caption/instant-apps-interactive-legend-layer-caption.scss
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-layer-caption/instant-apps-interactive-legend-layer-caption.tsx
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-relationship/instant-apps-interactive-legend-relationship.scss

- Bug fixes:
- Swap zoom/show all with collapsible actions
- Double scroll bar
- Dark mode support for relationship drawing style's instructional text

fix(interactive legend): bug fixes

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/assets/t9n/instant-apps-filter-list/resources.json
src/assets/t9n/instant-apps-filter-list/resources_en.json
src/components.d.ts
src/components/instant-apps-filter-list/instant-apps-filter-list.scss
src/components/instant-apps-filter-list/instant-apps-filter-list.tsx
src/components/instant-apps-filter-list/readme.md
src/components/instant-apps-filter-list/resources.ts
src/components/instant-apps-filter-list/test/instant-apps-filter-list.e2e.ts
src/components/instant-apps-filter-list/test/instant-apps-filter-list.spec.tsx
src/components/instant-apps-filter-list/utils.ts
src/index.html
src/interfaces/interfaces.d.ts
src/utils/mode.ts

I'll add a README before I merge.

Filter list

---

CHANGELOG.md
package-lock.json
package.json
src/assets/t9n/instant-apps-measurement/resources.json
src/assets/t9n/instant-apps-measurement/resources_en.json
src/components.d.ts
src/components/instant-apps-keyboard-shortcuts/instant-apps-keyboard-shortcuts.scss
src/components/instant-apps-keyboard-shortcuts/readme.md
src/components/instant-apps-measurement/instant-apps-measurement-tool/instant-apps-measurement-tool.scss
src/components/instant-apps-measurement/instant-apps-measurement-tool/instant-apps-measurement-tool.tsx
src/components/instant-apps-measurement/instant-apps-measurement-tool/readme.md
src/components/instant-apps-measurement/instant-apps-measurement.scss
src/components/instant-apps-measurement/instant-apps-measurement.tsx
src/components/instant-apps-measurement/readme.md
src/components/instant-apps-measurement/test/instant-apps-measurement.e2e.ts
src/components/instant-apps-measurement/test/instant-apps-measurement.spec.tsx
src/index.html
src/instant-apps-filter-list.html
src/instant-apps-header.html
src/instant-apps-interactive-legend.html
src/instant-apps-keyboard-shortcuts.html
src/instant-apps-measurement.html
src/instant-apps-popovers.html
src/instant-apps-social-share.html
src/interfaces/interfaces.d.ts

In Progress: 
Todo: 
- Add support for coordinate formats 
- Troubleshoot why esri css isn't applied to measure widget
- Add css variables (if needed) to style components

feat: Add measurement widget (in progress)

---

src/components/instant-apps-filter-list/instant-apps-filter-list.tsx

Brandon I made two updates for you to review. Feel free to reject if you have a better solution.

fix: Possible solution to url filter params

---

CHANGELOG.md
package.json
src/assets/t9n/instant-apps-filter-list/resources.json
src/assets/t9n/instant-apps-filter-list/resources_en.json
src/components/instant-apps-filter-list/instant-apps-filter-list.scss
src/components/instant-apps-filter-list/instant-apps-filter-list.tsx

https://devtopia.esri.com/WebGIS/arcgis-template-configuration/issues/2961

feat: add zoom to button

---

src/components.d.ts
src/components/instant-apps-header/instant-apps-header.tsx
src/components/instant-apps-header/readme.md
src/instant-apps-header.html

Added optional title text to button in header

feat: Add optional title text for info button in header component

---

src/components/instant-apps-header/instant-apps-header.scss
src/components/instant-apps-header/instant-apps-header.tsx
src/instant-apps-header.html

@kellyhutchins The previous update caused the build to fail because calcite-action needs the `text` prop. Changed to calcite-button to preserve the same look and updated icon color to be the same as header text color.

fix: update info button

---

CHANGELOG.md
package-lock.json
package.json
src/components.d.ts
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-classic/instant-apps-interactive-legend-classic.tsx
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-count/instant-apps-interactive-legend-count.tsx
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-group-legend-element-caption/instant-apps-interactive-legend-group-legend-element-caption.scss
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-group-legend-element-caption/instant-apps-interactive-legend-group-legend-element-caption.tsx
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-group-legend-element-caption/test/instant-apps-interactive-legend-group-legend-element-caption.e2e.ts
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-group-legend-element-caption/test/instant-apps-interactive-legend-group-legend-element-caption.spec.tsx
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-group-legend-element/instant-apps-interactive-legend-group-legend-element.scss
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-group-legend-element/instant-apps-interactive-legend-group-legend-element.tsx
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-group-legend-element/test/instant-apps-interactive-legend-group-legend-element.e2e.ts
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-group-legend-element/test/instant-apps-interactive-legend-group-legend-element.spec.tsx
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-legend-element-caption/instant-apps-interactive-legend-legend-element-caption.tsx
src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-legend-element/instant-apps-interactive-legend-legend-element.scss
src/components/instant-apps-interactive-legend/support/helpers.ts
src/instant-apps-interactive-legend.html

- Group layer visibility bug fix
- Feature count logic updates
- Nested unique category bug fixes

fix: instant-apps-interactive-legend groups and bug fixes

---

src/components.d.ts
src/components/instant-apps-measurement/instant-apps-measurement-tool/instant-apps-measurement-tool.scss
src/components/instant-apps-measurement/instant-apps-measurement-tool/instant-apps-measurement-tool.tsx
src/components/instant-apps-measurement/instant-apps-measurement.scss
src/components/instant-apps-measurement/instant-apps-measurement.tsx
src/instant-apps-measurement.html
src/interfaces/interfaces.d.ts

Updates to the Measure widget to: 
1. Style background of active tool
2. Allow active tool on startup
3.  Destroy tools when widget destroyed.

Measure enhancments

---

CHANGELOG.md
package-lock.json
package.json
src/components/instant-apps-interactive-legend/support/helpers.ts

fix: Use `activeLayerInfo.ready` instead of `activeLayerInfo.legendElements.length`.

Interactive Legend: Use activeLayerInfo.ready instead of activeLayerInfo.legendElements.length.

---

packages/instant-apps-components/package-lock.json
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components.d.ts
packages/instant-apps-components/src/components/instant-apps-scoreboard/instant-apps-scoreboard.tsx
packages/instant-apps-components/src/components/instant-apps-scoreboard/readme.md
packages/instant-apps-components/src/components/instant-apps-scoreboard/types/interfaces.d.ts
packages/instant-apps-components/src/index.html
packages/instant-apps-components/src/instant-apps-scoreboard-2.html

- Added additional sample
- Added property information to README

feat: Added property prevent auto docking in smaller viewports for Scoreboard

---

packages/instant-apps-components/package-lock.json
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components.d.ts
packages/instant-apps-components/src/components/instant-apps-scoreboard/instant-apps-scoreboard.tsx
packages/instant-apps-components/src/components/instant-apps-scoreboard/readme.md
packages/instant-apps-components/src/instant-apps-scoreboard-2.html

Scoreboard: Add property to optionally pass in geometry

---

packages/instant-apps-components/src/components.d.ts
packages/instant-apps-components/src/components/instant-apps-language-switcher/instant-apps-language-switcher.tsx
packages/instant-apps-components/src/components/instant-apps-language-switcher/readme.md
packages/instant-apps-components/src/components/instant-apps-language-translator/instant-apps-language-translator-item/instant-apps-language-translator-item.tsx
packages/instant-apps-components/src/components/instant-apps-language-translator/instant-apps-language-translator-item/readme.md
packages/instant-apps-components/src/components/instant-apps-language-translator/instant-apps-language-translator.tsx
packages/instant-apps-components/src/components/instant-apps-language-translator/readme.md
packages/instant-apps-components/src/components/instant-apps-language-translator/support/interfaces.d.ts
packages/instant-apps-components/src/utils/locale.ts

fix: load appropriate locale and handle map change (if available) on load, preserve user's default locale on refresh #206

#306: Language switcher issues and doc updates

---

packages/instant-apps-components/src/components/instant-apps-control-panel/instant-apps-control-panel.tsx
packages/instant-apps-components/src/components/instant-apps-control-panel/readme.md

This PR includes updates for the Control panel readme(added a description/screenshot) and updated descriptions for the 2 properties in the control panel .tsx file.

Updates for the Control panel component README

---

packages/instant-apps-components/package-lock.json
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components/instant-apps-language-switcher/instant-apps-language-switcher.tsx
packages/instant-apps-components/src/components/instant-apps-language-translator/instant-apps-language-translator.tsx
packages/instant-apps-components/src/components/instant-apps-language-translator/support/utils.ts
packages/instant-apps-components/src/utils/languageSwitcher.ts

fix: bust cache when requesting t9n data from portal item resource to get latest data within instant apps config

Language switcher fix

---

packages/instant-apps-components/src/components/instant-apps-control-panel/instant-apps-control-panel.tsx
packages/instant-apps-components/src/components/instant-apps-control-panel/readme.md
packages/instant-apps-components/src/components/instant-apps-export/instant-apps-export.tsx
packages/instant-apps-components/src/components/instant-apps-export/readme.md
packages/instant-apps-components/src/components/instant-apps-filter-list/instant-apps-filter-list.tsx
packages/instant-apps-components/src/components/instant-apps-filter-list/readme.md
packages/instant-apps-components/src/components/instant-apps-header/readme.md
packages/instant-apps-components/src/components/instant-apps-keyboard-shortcuts/instant-apps-keyboard-shortcuts.tsx
packages/instant-apps-components/src/components/instant-apps-keyboard-shortcuts/readme.md
packages/instant-apps-components/src/components/instant-apps-landing-page/readme.md
packages/instant-apps-components/src/components/instant-apps-measurement/instant-apps-measurement.tsx
packages/instant-apps-components/src/components/instant-apps-measurement/readme.md

Updated the readme files for Control panel, export, filter list, header, keyboard shortcuts, landing page and measurement tools

Updates to Readme and tsx files

---

packages/instant-apps-components/src/components/instant-apps-interactive-legend/instant-apps-interactive-legend.tsx
packages/instant-apps-components/src/components/instant-apps-interactive-legend/readme.md
packages/instant-apps-components/src/components/instant-apps-scoreboard/readme.md
packages/instant-apps-components/src/components/instant-apps-social-share/readme.md
packages/instant-apps-components/src/components/instant-apps-splash/readme.md

PR includes updates to the readme's for the scoreboard, splash, social sharing and interactive legend components.

Read me updates for scoreboard, splash, social sharing, and interactive legend 

---

packages/instant-apps-components/src/components/instant-apps-landing-page/readme.md
packages/instant-apps-components/src/components/instant-apps-measurement/readme.md
packages/instant-apps-components/src/components/instant-apps-popover/readme.md
packages/instant-apps-components/src/components/instant-apps-popovers/readme.md
packages/instant-apps-components/src/components/instant-apps-social-share/readme.md

Added descriptions for popover(s)
Made minor fixes to landing page, measure, social share Readme's

Updates for popover(s) Readme

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components/instant-apps-export/instant-apps-export.scss
packages/instant-apps-components/src/components/instant-apps-export/readme.md
packages/instant-apps-components/src/components/instant-apps-header/instant-apps-header.scss
packages/instant-apps-components/src/components/instant-apps-header/instant-apps-header.tsx
packages/instant-apps-components/src/components/instant-apps-social-share/instant-apps-social-share.scss
packages/instant-apps-components/src/components/instant-apps-social-share/instant-apps-social-share.tsx

https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/8660
- add optional action button background to export button
- update actions-end so that it doesn't have padding around it
Asked Lucy about this affecting other apps: 
> [Yesterday 11:37 AM] Lucy Gonzalez
>
>Hey Brandon would the change just require you to resize the header? If so I think it should be fine, I don't believe it'll have a negative impact on the other apps. I would also get rid of the space to the right 
https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/8720
- add container div around icon so that it can be properly centered

chore: css updates

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components/instant-apps-filter-list/instant-apps-filter-list.tsx

https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/8844

fix: Get layer's init definitionExpressions before initExpressions()

---

packages/instant-apps-components/package.json
packages/instant-apps-components/src/components/instant-apps-export/instant-apps-export.tsx

Not sure if this is the best approach but seems to work for #8952

fix: Update to ensure view is there before trying to use

---

.storybook/preview-head.html
packages/instant-apps-components/.storybook/preview-head.html
packages/instant-apps-components/README.md
packages/instant-apps-components/src/assets/t9n/instant-apps-measurement/resources.json
packages/instant-apps-components/src/assets/t9n/instant-apps-measurement/resources_en.json
packages/instant-apps-components/src/components.d.ts
packages/instant-apps-components/src/components/instant-apps-measurement/instant-apps-measurement-tool/instant-apps-measurement-tool.scss
packages/instant-apps-components/src/components/instant-apps-measurement/instant-apps-measurement-tool/instant-apps-measurement-tool.tsx
packages/instant-apps-components/src/components/instant-apps-measurement/instant-apps-measurement-tool/readme.md
packages/instant-apps-components/src/components/instant-apps-measurement/instant-apps-measurement.scss
packages/instant-apps-components/src/components/instant-apps-measurement/instant-apps-measurement.tsx
packages/instant-apps-components/src/instant-apps-measurement.html
packages/instant-apps-components/src/interfaces/interfaces.d.ts

- Update measure widget styles and get rid of stencil errors
- Update measure read-me to include all props
- Update storybook html pages so storybook will run successfully

Measure widget style update

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package-lock.json
packages/instant-apps-components/package.json
packages/instant-apps-components/stencil.config.ts

this is due to upgrading stencil to v4.7.2 based on calcite 2.0's stencil version

fix: use customElementsExportBehavior with autoDefineCustomElements in stencil.config.ts

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package-lock.json
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components.d.ts
packages/instant-apps-components/src/components/instant-apps-landing-page/instant-apps-landing-page.tsx
packages/instant-apps-components/src/components/instant-apps-landing-page/readme.md
packages/instant-apps-components/src/instant-apps-landing-page.html

feat: Added `landingPageOpen` and `landingPageClose` events that are emitted when the landing page is opened or closed, respectively.

instant-apps-landing-page: Open/close events

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components.d.ts
packages/instant-apps-components/src/components/instant-apps-language-translator/instant-apps-language-translator.tsx
packages/instant-apps-components/src/components/instant-apps-language-translator/readme.md
packages/instant-apps-components/src/instant-apps-language-translator.html

feat: Exposed public methods to use for custom actions.

Updates for instant-apps-language-translator

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package-lock.json
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components.d.ts
packages/instant-apps-components/src/components/instant-apps-language-translator/instant-apps-language-translator.tsx
packages/instant-apps-components/src/components/instant-apps-language-translator/readme.md

feat: batchWriteToPortalItemResource - Exposed public method to batch write to portal item resource.

instant-apps-language-translator: batchWriteToPortalItemResource

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package-lock.json
packages/instant-apps-components/package.json

When you all publish do you just update the version and then run that action workflow. The workflow part is new to me. Does it auto update the changelog?

update version for publish

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package-lock.json
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components/instant-apps-language-translator/instant-apps-language-translator.tsx
packages/instant-apps-components/src/components/instant-apps-language-translator/readme.md

feat: added a slot for a custom action, `translation-custom-action`, that will be placed in the translation header section of the UI.

Language translator action slot

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components/instant-apps-filter-list/instant-apps-filter-list.tsx
packages/instant-apps-components/src/interfaces/interfaces.d.ts

https://devtopia.esri.com/WebGIS/arcgis-template-configuration/issues/4314

fix: format dates

---

packages/instant-apps-components/src/components/instant-apps-filter-list/instant-apps-filter-list.tsx

[Issue 9626 in arcgis ](https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/9626)

add overlay positioning arg for the combobox

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package.json

Changes in https://github.com/Esri/instant-apps-components/pull/327

update version and changelog for publish

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components/instant-apps-export/instant-apps-export.tsx
packages/instant-apps-components/src/components/instant-apps-export/resources.ts

https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/9730

fix: update legend id and add legend.activeLayerInfo  checks

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package-lock.json
packages/instant-apps-components/package.json
packages/instant-apps-components/src/assets/t9n/instant-apps-social-share/resources.json
packages/instant-apps-components/src/assets/t9n/instant-apps-social-share/resources_en.json
packages/instant-apps-components/src/components/instant-apps-social-share/instant-apps-social-share.scss
packages/instant-apps-components/src/components/instant-apps-social-share/instant-apps-social-share.tsx

feat: Update 'Twitter' to 'X'

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package-lock.json
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components/instant-apps-create/instant-apps-create.tsx
packages/instant-apps-components/src/components/instant-apps-filter-list/instant-apps-filter-list.tsx
packages/instant-apps-components/src/components/instant-apps-interactive-legend/instant-apps-interactive-legend-classic/instant-apps-interactive-legend-classic.tsx
packages/instant-apps-components/src/components/instant-apps-interactive-legend/support/helpers.ts
packages/instant-apps-components/src/components/instant-apps-sign-in/instant-apps-sign-in.tsx

Other:
- Resolve compiler errrors

Interactive Legend fixes

---

packages/instant-apps-components/package-lock.json
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components/instant-apps-control-panel/instant-apps-control-panel.test.ts
packages/instant-apps-components/src/components/instant-apps-create/instant-apps-create.test.ts
packages/instant-apps-components/src/components/instant-apps-create/instant-apps-create.tsx
packages/instant-apps-components/src/components/instant-apps-language-translator/instant-apps-language-translator.tsx
packages/instant-apps-components/src/utils/locale.ts
packages/instant-apps-components/vite.config.ts
packages/instant-apps-components/vitest.config.ts

fyi @JaylenHoLuc, Going to merge this PR into your test branch and will cherry pick my fix into master afterwards.

Updates to handle translation files in test environment

---

packages/instant-apps-components/src/components/instant-apps-control-panel/instant-apps-control-panel.test.ts
packages/instant-apps-components/src/components/instant-apps-create/instant-apps-create.test.ts
packages/instant-apps-components/src/components/instant-apps-header/instant-apps-header.test.ts
packages/instant-apps-components/src/components/instant-apps-landing-page/instant-apps-landing-page.test.ts
packages/instant-apps-components/src/components/instant-apps-social-share/instant-apps-social-share.test.ts

Added Unit tests for control panel, create, header, landing page, and social share

Added Unit tests 

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components/instant-apps-landing-page/instant-apps-landing-page.scss
packages/instant-apps-components/src/components/instant-apps-landing-page/instant-apps-landing-page.tsx
packages/instant-apps-components/src/components/instant-apps-sign-in/instant-apps-sign-in.scss
packages/instant-apps-components/src/components/instant-apps-sign-in/instant-apps-sign-in.tsx
packages/instant-apps-components/src/instant-apps-landing-page-2.html

- Update landing page's sign in UI
- Update sign in/out logic

chore: update sign-in UI and logic

---

packages/instant-apps-components/src/assets/t9n/instant-apps-app-guide/resources.json
packages/instant-apps-components/src/assets/t9n/instant-apps-app-guide/resources_en.json

- Adds string files for the App Guide component
PR for the component itself will be posted soon

chore: add t9n files  for app guide component

---

packages/instant-apps-components-react/src/components/stencil-generated/index.ts
packages/instant-apps-components/src/components.d.ts
packages/instant-apps-components/src/components/instant-apps-app-guide/instant-apps-app-guide.scss
packages/instant-apps-components/src/components/instant-apps-app-guide/instant-apps-app-guide.tsx
packages/instant-apps-components/src/components/instant-apps-app-guide/readme.md
packages/instant-apps-components/src/components/instant-apps-app-guide/test/instant-apps-app-guide.e2e.ts
packages/instant-apps-components/src/components/instant-apps-app-guide/test/instant-apps-app-guide.spec.tsx

Adding the base files for the new App Guide component.

feat: starter files for the App Guide component

---

packages/instant-apps-components/package.json
packages/instant-apps-components/src/components.d.ts
packages/instant-apps-components/src/components/instant-apps-filter-list/instant-apps-filter-list.tsx

https://github.com/Esri/solutions-components/issues/868

Filter list update

---

packages/instant-apps-components/src/components/instant-apps-splash/__tests__/instant-apps-splash.test.ts

Basic tests for Splash component

Instant apps splash

---

packages/instant-apps-components/src/assets/t9n/instant-apps-app-guide/resources.json
packages/instant-apps-components/src/assets/t9n/instant-apps-app-guide/resources_en.json
packages/instant-apps-components/src/components.d.ts
packages/instant-apps-components/src/components/instant-apps-app-guide/AppGuide/AppGuideViewModel.ts
packages/instant-apps-components/src/components/instant-apps-app-guide/instant-apps-app-guide.scss
packages/instant-apps-components/src/components/instant-apps-app-guide/instant-apps-app-guide.tsx
packages/instant-apps-components/src/components/instant-apps-app-guide/readme.md
packages/instant-apps-components/src/instant-apps-app-guide.html

* Added styling for the lists layout
* Header updates based on feedback from the team

feat: header text and list style updates in the App Guide component

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package-lock.json
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components/instant-apps-time-filter/TimeFilter/TimeFilterViewModel.ts
packages/instant-apps-components/src/components/instant-apps-time-filter/TimeFilter/interfaces/interfaces.d.ts

fix(time filter): properly instantiate time slider if type in config is set to 'map'

Time Filter: Type is set to map

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package-lock.json
packages/instant-apps-components/package.json

Update package.json and changelog.md for App Guide component to v1.0.0-beta.265

chore: update package.json and changelog.md for App Guide component

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package-lock.json
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components/instant-apps-app-guide/instant-apps-app-guide.tsx
packages/instant-apps-components/src/components/instant-apps-app-guide/readme.md

Updates based on dev feedback during integration

refactor: handling of null values in page titles + enable header by default

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package-lock.json
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components/instant-apps-export/instant-apps-export.tsx
packages/instant-apps-components/src/components/instant-apps-sign-in/instant-apps-sign-in.tsx

- add `user-id` to calcite-avatar
- add `respectLayerDefinitionExpression` to Legend

chore: minor updates

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package-lock.json
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components/instant-apps-app-guide/AppGuide/AppGuideViewModel.ts
packages/instant-apps-components/src/components/instant-apps-app-guide/instant-apps-app-guide.tsx

Refactoring to address the component header text not being set properly when certain race conditions occur within the context of an app.

refactor: update view model and component concerns

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package-lock.json
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components.d.ts
packages/instant-apps-components/src/components/instant-apps-landing-page/instant-apps-landing-page.scss
packages/instant-apps-components/src/components/instant-apps-landing-page/instant-apps-landing-page.tsx
packages/instant-apps-components/src/components/instant-apps-sign-in/instant-apps-sign-in.scss
packages/instant-apps-components/src/components/instant-apps-sign-in/instant-apps-sign-in.tsx
packages/instant-apps-components/src/components/instant-apps-sign-in/readme.md

- add `showIndicator` prop to show blue indicator on users avatar
- update CSS and width props of sign in buttons
- use Promise to pause render until check is over in landing page
- fix: only run check with whenOnce if user is signed in

chore: update sign-in and landing-page components

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components/instant-apps-filter-list/instant-apps-filter-list.tsx

use handleURLParams() before initExpressions()

fix: URL params and dropdown

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package-lock.json
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components/instant-apps-filter-list/instant-apps-filter-list.tsx

update how filter list handles lifecycle methods. Add check for footer buttons, change width to full when only one is visible.

fix: filter list bug fixes

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components/instant-apps-filter-list/instant-apps-filter-list.tsx

https://github.com/Esri/solutions-components/issues/965

don't clone on reset

---

packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package-lock.json
packages/instant-apps-components/package.json
packages/instant-apps-components/src/components/instant-apps-filter-list/instant-apps-filter-list.tsx

fix: remove unnecessary update of expression.active, turn loading el off when no layer expression, update reset button disabled in componentDidRender

fixes to filter-list:

---

packages/instant-apps-components/src/components/instant-apps-measurement/instant-apps-measurement.tsx

Keyboard shortcuts looks ok measurement just needed one minor update

Kelly component update

---

package-lock.json
packages/instant-apps-components/CHANGELOG.md
packages/instant-apps-components/package.json

Forgot to update version number and changelog

chore: update version num
